##################################################
# 共通設定値
##################################################
default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

##################################################
# 開発環境
##################################################
development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host:     <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

##################################################
# テスト環境
##################################################
test:
  <<: *default
  database: "dig_live_test"
  host:     <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

##################################################
# 本番環境
##################################################
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host:     <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
